using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/** <summary>
This class takes a ToonRampGenerator_SO sciptable object and is responsible
for broadcasting the tramp texstures (generated by the scriptable object) to 
the listeners (ToonRampReceiver) attached to gameobjects in scene
</summary> **/

[ExecuteAlways]
public class ToonRampListener : MonoBehaviour
{
    [SerializeField] List<ToonRampGenerator_SO> toonRampGeneratorList_SO;

    public event System.Action<Texture2D, Texture2D> OnRampsUpdate;

    public static ToonRampListener Instance;

    private void DoSingletonStuff()
    {
        if (Instance != null && Instance != this)
        {
            Debug.LogError("Attempt to create additional instance of ToonRampBroadcaster (Singleton)");
            Destroy(gameObject);
        }
        else
        {
            Instance = this;
        }
    }

    void Awake()
    {
        DoSingletonStuff();
    }

    void Update()
    {
        foreach(ToonRampGenerator_SO toonRampGenerator_SO in toonRampGeneratorList_SO)
        {
            if (toonRampGenerator_SO != null && toonRampGenerator_SO.ShouldUpdateRamps)
            {
                toonRampGenerator_SO.ShouldUpdateRamps = false;
                toonRampGenerator_SO.GenerateRampTextures();
            }
        }
    }
}
